# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_info_country', models.CharField(max_length=25)),
                ('city_info_region', models.CharField(max_length=25)),
                ('city_info_city', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'city_info',
            },
        ),
    ]
