# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_id', models.IntegerField()),
                ('orders_product', models.CharField(max_length=25)),
                ('orders_customer', models.CharField(max_length=25)),
                ('orders_quantity', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
